# Generated by Django 3.1.4 on 2020-12-19 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('specie', models.CharField(choices=[('DO', 'Dog'), ('CA', 'Cat'), ('FE', 'Ferret'), ('RA', 'Rabbit')], default='DO', max_length=2)),
                ('description', models.CharField(max_length=245)),
                ('age', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.pets')),
            ],
            options={
                'db_table': 'breeds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.users')),
                ('name', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'people',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placelost', models.CharField(max_length=100)),
                ('datelost', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(choices=[('HO', 'Home'), ('LO', 'LOST'), ('FO', 'FOUNDED')], default='HO', max_length=2)),
                ('placefounded', models.CharField(max_length=100)),
                ('datefounded', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('pet_id_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pets')),
                ('people_id_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.people')),
            ],
            options={
                'db_table': 'reports',
                'managed': True,
            },
        ),
    ]
